# Generated by Django 6.0.6 on 2026-06-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='contact_info',
            field=models.TextField(blank=True),
        ),
    ]
