# Generated by Django 6.0.6 on 2026-06-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_calendarevent_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('competition', models.CharField(blank=True, help_text='Which competition this problem is from, e.g. 2025 Kentucky Mining Institute Contest', max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='problems/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
    ]
