# Generated by Django 6.0.6 on 2026-06-11 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_competition_grouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='calendar_event',
            field=models.ForeignKey(blank=True, help_text='Calendar entry for this competition. Matched automatically by name and year when possible; set it here to override.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='pages.calendarevent'),
        ),
    ]
