# Generated by Django 6.0.6 on 2026-06-11 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_competition_calendar_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='calendar_event',
            field=models.ForeignKey(blank=True, help_text="Calendar entry for this competition. Matched automatically within the same year by comparing this competition's name to event titles and locations; set it here to override.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='pages.calendarevent'),
        ),
    ]
