# Generated by Django 6.0.6 on 2026-06-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_competition_calendar_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='resources',
            field=models.JSONField(blank=True, default=dict, help_text="Links to registration, results, rules, flyers, etc. Format: {'registration': 'url', 'results': 'url', ...}"),
        ),
    ]
