# Generated by Django 6.0.6 on 2026-06-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_calendarevent_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='resources',
            field=models.JSONField(blank=True, default=list, help_text='Links to results, registration forms, flyers, etc. Format: [{"label": "Final Results", "url": "https://..."}, ...]'),
        ),
    ]
