# Generated by Django 6.0.6 on 2026-06-18 01:57

from django.db import migrations, models

# The link previously hard-coded in calendar.html; seeded so the button keeps
# working after deploy. It is admin-editable from here on.
MSHA_2026_URL = (
    "https://www.msha.gov/training/training/mine-rescue-training/"
    "mine-rescue-contests/2026-enforcement-mine-rescue-contest"
)


def seed_msha_url(apps, schema_editor):
    SiteConfiguration = apps.get_model('pages', 'SiteConfiguration')
    SiteConfiguration.objects.get_or_create(
        pk=1, defaults={'msha_calendar_url': MSHA_2026_URL}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_calendarevent_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msha_calendar_url', models.URLField(blank=True, help_text='URL for the “Official MSHA Contest Calendar” button on the Competition Calendar page. Update it when MSHA posts the next season’s contest page. Leave blank to hide the button.', max_length=500, verbose_name='MSHA calendar link')),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
        migrations.RunPython(seed_msha_url, migrations.RunPython.noop),
    ]
