# Generated by Django 6.0.6 on 2026-07-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionRuleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Section I: Coal Mine Rescue Rules', max_length=255)),
                ('file', models.FileField(upload_to='training/rules/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Documents are listed lowest number first')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InstructionGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Unified Mine Rescue Training (Advanced) — IG 115', max_length=255)),
                ('description', models.TextField(help_text="What this guide covers and who it's for")),
                ('file', models.FileField(upload_to='training/igs/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Guides are listed lowest number first')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. A Card - Map', max_length=255)),
                ('fillable_file', models.FileField(blank=True, upload_to='training/scorecards/')),
                ('non_fillable_file', models.FileField(blank=True, upload_to='training/scorecards/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Scorecards are listed lowest number first')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
