# Generated by Django 6.0.6 on 2026-07-12 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_competitionruledocument_instructionguide_scorecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. First Aid Written Test', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Quizzes are listed lowest number first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='pages.competitionproblem')),
                ('source_document', models.ForeignKey(blank=True, help_text='The original test PDF this quiz was extracted from (for the Take Test button).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.problemdocument')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pages.quiz')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='pages.quizquestion')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
