# Generated by Django 6.0.6 on 2026-07-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_quiz_quizquestion_quizchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='image',
            field=models.FileField(blank=True, help_text='Diagram/figure shown with the question (e.g. a parts illustration the question refers to).', upload_to='quiz_images/'),
        ),
    ]
