# Generated by Django 6.0.6 on 2026-07-16 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_quizquestion_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchingApparatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Draeger PSS BG4 plus', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Optional note shown above the unit's resource list")),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Units are listed lowest number first')),
            ],
            options={
                'verbose_name_plural': 'Benching apparatus',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BenchingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. PSS BG 4 / PSS BG 4 plus - Instructions for Use', max_length=255)),
                ('description', models.TextField(blank=True, help_text='What this document covers')),
                ('file', models.FileField(blank=True, help_text='The document to preview/download. Leave blank for a link-only resource (e.g. software hosted elsewhere) and set the source link below.', upload_to='training/benching/')),
                ('source_url', models.URLField(blank=True, help_text="External link for this resource, e.g. the manufacturer's page or hosted software. Shown as a link alongside (or instead of) the file.")),
                ('link_label', models.CharField(blank=True, help_text="Text for the source link, e.g. 'Access software'. Defaults to 'Source'.", max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Resources are listed lowest number first')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apparatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='pages.benchingapparatus')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
