# Generated by Django 6.0.6 on 2026-07-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_benchingapparatus_benchingresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. First Aid Field Reference', max_length=255)),
                ('description', models.TextField(blank=True, help_text='What this document covers')),
                ('file', models.FileField(upload_to='training/first_aid/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Documents are listed lowest number first')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RopeRescueResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. High Angle Rope Rescue Guide', max_length=255)),
                ('description', models.TextField(blank=True, help_text='What this document covers')),
                ('file', models.FileField(upload_to='training/rope_rescue/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Documents are listed lowest number first')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
