# Generated by Django 6.0.6 on 2026-07-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_firstaidresource_roperescueresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchingresource',
            name='is_sds',
            field=models.BooleanField(default=False, help_text="Show this resource in the unit's collapsible Safety Data Sheets group instead of the main list", verbose_name='Safety Data Sheet'),
        ),
    ]
