# Generated by Django 6.0.6 on 2026-09-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_benchingresource_is_sds'),
    ]

    operations = [
        migrations.AddField(
            model_name='roperescueresource',
            name='link_label',
            field=models.CharField(blank=True, help_text="Text for the source link, e.g. 'View on Amazon'. Defaults to 'Source'.", max_length=60),
        ),
        migrations.AddField(
            model_name='roperescueresource',
            name='source_url',
            field=models.URLField(blank=True, help_text='External link for this resource, e.g. where to buy a book. Shown as a link alongside (or instead of) the file.'),
        ),
        migrations.AlterField(
            model_name='roperescueresource',
            name='file',
            field=models.FileField(blank=True, help_text='The document to preview/download. Leave blank for a link-only resource (e.g. a book sold elsewhere) and set the source link below.', upload_to='training/rope_rescue/'),
        ),
    ]
