# Generated by Django 6.0.6 on 2026-09-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_roperescueresource_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdocument',
            name='answer_key',
            field=models.FileField(blank=True, help_text="Answer key for a written test. Shown as a Key button on this document's row instead of as a separate document.", upload_to='problems/'),
        ),
    ]
