# Generated by Django 6.0.6 on 2026-10-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_problemdocument_answer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='sort_date',
            field=models.DateField(blank=True, help_text="Only used to order the past-problems list when there is no calendar event (the real date isn't known). Never shown.", null=True),
        ),
    ]
