# Generated by Django 6.0.6 on 2026-10-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_geocodedlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastRuleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='Contest year the rules were issued for')),
                ('title', models.CharField(help_text='e.g. Coal Mine Rescue Rules', max_length=255)),
                ('file', models.FileField(upload_to='training/rules/past/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Within a year, documents are listed lowest number first')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'sort_order', 'title'],
            },
        ),
    ]
