# Generated by Django 6.0.6 on 2026-10-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_pastruledocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(help_text='e.g. Colorado Regional Mine Rescue Contest', max_length=200),
        ),
    ]
