# Generated by Django 6.0.6 on 2026-10-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_competition_name_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionruledocument',
            name='companion_file',
            field=models.FileField(blank=True, help_text='A form that goes with these rules, e.g. the blank preshift record report. Shown as a button on this row instead of as its own document.', upload_to='training/rules/'),
        ),
        migrations.AddField(
            model_name='competitionruledocument',
            name='companion_label',
            field=models.CharField(blank=True, help_text='Button text for the companion file, e.g. Blank Report', max_length=40),
        ),
    ]
